# Generated by Django 3.0.7 on 2020-06-15 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('course_student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
