# Generated by Django 3.0.6 on 2020-06-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Choose_Courses', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
