# Generated by Django 3.0.6 on 2020-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choose_Courses', '0003_auto_20200607_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='Choose_Courses.Course'),
        ),
    ]
