# Generated by Django 3.0 on 2020-06-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('courseID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='coursePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixSet', to='course.course')),
                ('suffix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suffixSet', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='courseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haveLearnt', models.BooleanField()),
                ('chosenCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
