# Generated by Django 3.0 on 2020-06-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haveLearnt', models.BooleanField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultSet', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnerSet', to='course.course')),
            ],
        ),
        migrations.AlterField(
            model_name='courseprefix',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suffixSet', to='course.course'),
        ),
        migrations.AlterField(
            model_name='courseprefix',
            name='suffix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixSet', to='course.course'),
        ),
        migrations.DeleteModel(
            name='courseChoice',
        ),
    ]
